config/routes.rb
GardenApp::Application.routes.draw do
  resources :flower_twos

  resources :flowers

  resources :beds

end

app/models/bed.rb
class Bed < ActiveRecord::Base
  has_many :flower_twos

end

app/models/flower.rb
class Flower < ActiveRecord::Base
end

app/models/flower_two.rb
class FlowerTwo < ActiveRecord::Base
  belongs_to :bed
  
  validates :latin_name, :length => { :maximum => 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/beds_controller.rb
class BedsController < ApplicationController
  # GET /beds
  # GET /beds.xml
  def index
    @beds = Bed.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @beds }
    end
  end

  # GET /beds/1
  # GET /beds/1.xml
  def show
    @bed = Bed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bed }
    end
  end

  # GET /beds/new
  # GET /beds/new.xml
  def new
    @bed = Bed.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bed }
    end
  end

  # GET /beds/1/edit
  def edit
    @bed = Bed.find(params[:id])
  end

  # POST /beds
  # POST /beds.xml
  def create
    @bed = Bed.new(params[:bed])

    respond_to do |format|
      if @bed.save
        format.html { redirect_to(@bed, :notice => 'Bed was successfully created.') }
        format.xml  { render :xml => @bed, :status => :created, :location => @bed }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /beds/1
  # PUT /beds/1.xml
  def update
    @bed = Bed.find(params[:id])

    respond_to do |format|
      if @bed.update_attributes(params[:bed])
        format.html { redirect_to(@bed, :notice => 'Bed was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /beds/1
  # DELETE /beds/1.xml
  def destroy
    @bed = Bed.find(params[:id])
    @bed.destroy

    respond_to do |format|
      format.html { redirect_to(beds_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/flower_twos_controller.rb
class FlowerTwosController < ApplicationController
  # GET /flower_twos
  # GET /flower_twos.xml
  def index
    @flower_twos = FlowerTwo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @flower_twos }
    end
  end

  # GET /flower_twos/1
  # GET /flower_twos/1.xml
  def show
    @flower_two = FlowerTwo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @flower_two }
    end
  end

  # GET /flower_twos/new
  # GET /flower_twos/new.xml
  def new
    @flower_two = FlowerTwo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @flower_two }
    end
  end

  # GET /flower_twos/1/edit
  def edit
    @flower_two = FlowerTwo.find(params[:id])
  end

  # POST /flower_twos
  # POST /flower_twos.xml
  def create
    @flower_two = FlowerTwo.new(params[:flower_two])

    respond_to do |format|
      if @flower_two.save
        format.html { redirect_to(@flower_two, :notice => 'Flower two was successfully created.') }
        format.xml  { render :xml => @flower_two, :status => :created, :location => @flower_two }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @flower_two.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /flower_twos/1
  # PUT /flower_twos/1.xml
  def update
    @flower_two = FlowerTwo.find(params[:id])

    respond_to do |format|
      if @flower_two.update_attributes(params[:flower_two])
        format.html { redirect_to(@flower_two, :notice => 'Flower two was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @flower_two.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /flower_twos/1
  # DELETE /flower_twos/1.xml
  def destroy
    @flower_two = FlowerTwo.find(params[:id])
    @flower_two.destroy

    respond_to do |format|
      format.html { redirect_to(flower_twos_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  # GET /flowers
  # GET /flowers.xml
  def index
    @flowers = Flower.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @flowers }
    end
  end

  # GET /flowers/1
  # GET /flowers/1.xml
  def show
    @flower = Flower.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @flower }
    end
  end

  # GET /flowers/new
  # GET /flowers/new.xml
  def new
    @flower = Flower.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @flower }
    end
  end

  # GET /flowers/1/edit
  def edit
    @flower = Flower.find(params[:id])
  end

  # POST /flowers
  # POST /flowers.xml
  def create
    @flower = Flower.new(params[:flower])

    respond_to do |format|
      if @flower.save
        format.html { redirect_to(@flower, :notice => 'Flower was successfully created.') }
        format.xml  { render :xml => @flower, :status => :created, :location => @flower }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @flower.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /flowers/1
  # PUT /flowers/1.xml
  def update
    @flower = Flower.find(params[:id])

    respond_to do |format|
      if @flower.update_attributes(params[:flower])
        format.html { redirect_to(@flower, :notice => 'Flower was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @flower.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /flowers/1
  # DELETE /flowers/1.xml
  def destroy
    @flower = Flower.find(params[:id])
    @flower.destroy

    respond_to do |format|
      format.html { redirect_to(flowers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beds_helper.rb
module BedsHelper
end

app/helpers/flower_twos_helper.rb
module FlowerTwosHelper
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/views/beds/_form.html.erb
<%= form_for(@bed) do |f| %>
  <% if @bed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bed.errors.count, "error") %> prohibited this bed from being saved:</h2>

      <ul>
      <% @bed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :soil_type %><br />
    <%= f.text_field :soil_type %>
  </div>
  <div class="field">
    <%= f.label :sqft %><br />
    <%= f.text_field :sqft %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beds/edit.html.erb
<h1>Editing bed</h1>

<%= render 'form' %>

<%= link_to 'Show', @bed %> |
<%= link_to 'Back', beds_path %>

app/views/beds/index.html.erb
<h1>Listing beds</h1>

<table>
  <tr>
    <th>Soil type</th>
    <th>Sqft</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @beds.each do |bed| %>
  <tr>
    <td><%= bed.soil_type %></td>
    <td><%= bed.sqft %></td>
    <td><%= link_to 'Show', bed %></td>
    <td><%= link_to 'Edit', edit_bed_path(bed) %></td>
    <td><%= link_to 'Destroy', bed, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bed', new_bed_path %>

app/views/beds/new.html.erb
<h1>New bed</h1>

<%= render 'form' %>

<%= link_to 'Back', beds_path %>

app/views/beds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Soil type:</b>
  <%= @bed.soil_type %>
</p>

<p>
  <b>Sqft:</b>
  <%= @bed.sqft %>
</p>


<%= link_to 'Edit', edit_bed_path(@bed) %> |
<%= link_to 'Back', beds_path %>

app/views/flower_twos/_form.html.erb
<%= form_for(@flower_two) do |f| %>
  <% if @flower_two.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flower_two.errors.count, "error") %> prohibited this flower_two from being saved:</h2>

      <ul>
      <% @flower_two.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latin_name %><br />
    <%= f.text_field :latin_name %>
  </div>
  <div class="field">
    <%= f.label :common_name %><br />
    <%= f.text_field :common_name %>
  </div>
  <div class="field">
    <%= f.label :bed_id %><br />
    <%= f.text_field :bed_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flower_twos/edit.html.erb
<h1>Editing flower_two</h1>

<%= render 'form' %>

<%= link_to 'Show', @flower_two %> |
<%= link_to 'Back', flower_twos_path %>

app/views/flower_twos/index.html.erb
<h1>Listing flower_twos</h1>

<table>
  <tr>
    <th>Latin name</th>
    <th>Common name</th>
    <th>Bed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @flower_twos.each do |flower_two| %>
  <tr>
    <td><%= flower_two.latin_name %></td>
    <td><%= flower_two.common_name %></td>
    <td><%= flower_two.bed_id %></td>
    <td><%= link_to 'Show', flower_two %></td>
    <td><%= link_to 'Edit', edit_flower_two_path(flower_two) %></td>
    <td><%= link_to 'Destroy', flower_two, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Flower two', new_flower_two_path %>

app/views/flower_twos/new.html.erb
<h1>New flower_two</h1>

<%= render 'form' %>

<%= link_to 'Back', flower_twos_path %>

app/views/flower_twos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Latin name:</b>
  <%= @flower_two.latin_name %>
</p>

<p>
  <b>Common name:</b>
  <%= @flower_two.common_name %>
</p>

<p>
  <b>Bed:</b>
  <%= @flower_two.bed_id %>
</p>


<%= link_to 'Edit', edit_flower_two_path(@flower_two) %> |
<%= link_to 'Back', flower_twos_path %>

app/views/flowers/_form.html.erb
<%= form_for(@flower) do |f| %>
  <% if @flower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flower.errors.count, "error") %> prohibited this flower from being saved:</h2>

      <ul>
      <% @flower.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latin_name %><br />
    <%= f.text_field :latin_name %>
  </div>
  <div class="field">
    <%= f.label :common_name %><br />
    <%= f.text_field :common_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flowers/edit.html.erb
<h1>Editing flower</h1>

<%= render 'form' %>

<%= link_to 'Show', @flower %> |
<%= link_to 'Back', flowers_path %>

app/views/flowers/index.html.erb
<h1>Listing flowers</h1>

<table>
  <tr>
    <th>Latin name</th>
    <th>Common name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @flowers.each do |flower| %>
  <tr>
    <td><%= flower.latin_name %></td>
    <td><%= flower.common_name %></td>
    <td><%= link_to 'Show', flower %></td>
    <td><%= link_to 'Edit', edit_flower_path(flower) %></td>
    <td><%= link_to 'Destroy', flower, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Flower', new_flower_path %>

app/views/flowers/new.html.erb
<h1>New flower</h1>

<%= render 'form' %>

<%= link_to 'Back', flowers_path %>

app/views/flowers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Latin name:</b>
  <%= @flower.latin_name %>
</p>

<p>
  <b>Common name:</b>
  <%= @flower.common_name %>
</p>


<%= link_to 'Edit', edit_flower_path(@flower) %> |
<%= link_to 'Back', flowers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GardenApp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>